theme: jekyll-theme-architect
title: Loretta
brief-intro: Just a programmer
url: "https://Loretta199.github.io/" 

permalink: /:year/:month/:day/:title/

description_footer: 时间无多,疾步前行

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: loretta

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

category_dir: category/
tag_dir: tag/

excerpt_separator: "\n\n\n\n"

gems: [jekyll-paginate]
paginate: 6